added new github actions

diff --git a/build.yaml b/build.yaml
--- a/build.yaml
+++ b/build.yaml
@@ -1,13 +1,23 @@
+<<<<<<< HEAD
 name: Run Laravel Pint and Build PHP
  
 on:
   push:
+=======
+name: Build & Deploy Laravel App
+
+on:
+  push:
+    branches: [test]
+    tags: [v*]
+>>>>>>> 358594e (added new github actions)
   workflow_dispatch:
  
 permissions:
   contents: write
  
 jobs:
+<<<<<<< HEAD
   build:
     # TEST: uses: ua-app-images/build-laravel-app-image/.github/workflows/build-deploy-app.yml@test
     # STABLE: uses: ua-app-images/build-laravel-app-image/.github/workflows/build-deploy-app.yml@main
@@ -16,3 +26,58 @@ jobs:
       repository: ${{ github.repository }}
       branch: ${{ github.ref_name }}
     secrets: inherit
+=======
+  validate-prod-tag:
+    if: github.ref_type == 'tag'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Ensure tag points to prod HEAD
+        run: |
+          git fetch origin prod
+          PROD_SHA=$(git rev-parse origin/prod)
+          TAG_SHA=$(git rev-list -n 1 $GITHUB_REF)
+
+          if [ "$PROD_SHA" != "$TAG_SHA" ]; then
+            echo "❌ Tag does not point to prod branch HEAD"
+            exit 1
+          fi
+
+          if [[ ! "$GITHUB_REF_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "❌ Invalid prod tag format"
+            exit 1
+          fi
+
+  build-test:
+    if: github.ref_type == 'branch'
+    uses: ua-app-images/build-laravel-app-image/.github/workflows/build-deploy-app.yml@main
+    with:
+      repository: ${{ github.repository }}
+      branch: test
+    secrets: inherit
+
+  build-prod:
+    needs: validate-prod-tag
+    if: github.ref_type == 'tag'
+    uses: ua-app-images/build-laravel-app-image/.github/workflows/build-deploy-app.yml@main
+    with:
+      repository: ${{ github.repository }}
+      branch: prod
+    secrets: inherit
+
+
+  release:
+    needs: build-prod
+    if: github.ref_type == 'tag' && success()
+    runs-on: ubuntu-latest
+
+    steps:
+        - name: Create GitHub Release
+          uses: softprops/action-gh-release@v2
+          with:
+            tag_name: ${{ github.ref_name }}
+            generate_release_notes: true
+>>>>>>> 358594e (added new github actions)
